language: julia
os:
  - linux
julia:
  - 0.3
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
script:
  - git fetch --unshallow
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("ImmutableArrays", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ImmutableArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
